name: CI Pipeline

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master 

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          ls /TP2 and 3/services/epf-flower-data-science
          pip install -r ./TP2\ and\ 3/services/epf-flower-data-science/requirements.txt
          export PYTHONPATH="${PYTHONPATH}:./TP2 and 3/services/epf-flower-data-science"

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q
          
      - name: Upload test results
        if: failure()  
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./tests/test_results/
